# Generated by Django 4.2.2 on 2023-06-25 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='starttime',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Timeblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('detail', models.CharField(max_length=50)),
                ('timetable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_id', to='app.timetable')),
            ],
        ),
    ]
