# Generated by Django 4.2.2 on 2023-07-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_timetable_detail_remove_timetable_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_img', models.ImageField(blank=True, upload_to='')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.like')),
            ],
        ),
    ]
