# Generated by Django 4.2.2 on 2023-07-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='timetable_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_timetable', to='app.timetable'),
            preserve_default=False,
        ),
    ]
