# Generated by Django 4.2.2 on 2023-07-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_like_timetable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablelist',
            name='timetable_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_id_list', to='app.timetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='like',
            field=models.IntegerField(),
        ),
    ]
